from callback_functions.content import render_content
from callback_functions.sponsors import show_sponsor
from callback_functions.tables import update_table
from callback_functions.graphs import update_graph